name: Deploy to GitHub Pages

on:
  pull_request:
    branches:
      - main
    types:
      - closed
  push:
    branches:
      - main

jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write
 
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3
      - name: Setup Node.js and build your site
        run: |
          cd homepage
          npm install
          npm run build
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1
       
          
    environment:
        name: github-pages
        url: ${{ steps.deploy.outputs.page_url }}
